# Generated by Django 2.1.5 on 2024-01-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20240131_1320'),
        ('rango', '0002_alter_category_options'),
    ]

    operations = [
    ]
